#                          ______
#                       .-"      "-.
#                      /            \
#                     |              |
#                     |,  .-.  .-.  ,|
#                     | )(__/  \__)( |
#                     |/     /\     \|
#      (@_            (_     ^^     _)
# _     ) \____________\__|IIIIII|__/____________________
#(_)@8@8{}<_____________|-\IIIIII/-|_____________________>
#       )_/             \          /
#      (@                `--------` 
#

from colorama import Fore
import  os
import  time

# Copyright C 2021 By temirovazat

def Sword():
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print("                      "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print("                       "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"_                     "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_>                     "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"__                    "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"__>                    "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"___                   "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"___>                   "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"____                  "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"____>                  "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"_____                 "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_____>                 "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______                "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"______>                "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"_______               "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_______>               "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"________              "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"________>              "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"________              "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"________>              "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"_________             "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_________>             "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"__________            "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"__________>            "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"___________           "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"___________>           "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"____________          "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"____________>          "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"_____________         "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_____________>         "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________        "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"______________>        "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________       "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________>       "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"________________      "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"________________>      "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"________________      "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"________________>      "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"_________________     "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_________________>     "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"__________________    "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"__________________>    "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"___________________   "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"___________________>   "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"____________________  "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"____________________>  "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"_____________________ "+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_____________________> "+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________>"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+">")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+"_>")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"_")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+"__>")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"__")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+"___>")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"___")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+"____>")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"____")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+"_____>")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"_____")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+"______>")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print("                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(""+Fore.LIGHTMAGENTA_EX+"______________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"______")
    print(""+Fore.LIGHTMAGENTA_EX+"_______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+"_______>")
    print("                       "+Fore.LIGHTCYAN_EX+"\          /")
    print("                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print(Fore.LIGHTGREEN_EX+"                     "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(Fore.LIGHTGREEN_EX+"\\"+Fore.LIGHTMAGENTA_EX+"_____________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"_______")
    print(Fore.LIGHTGREEN_EX+""+Fore.LIGHTMAGENTA_EX+"<______________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+"________>")
    print(Fore.LIGHTGREEN_EX+"/                      "+Fore.LIGHTCYAN_EX+"\          /")
    print(Fore.LIGHTGREEN_EX+"                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print(Fore.LIGHTGREEN_EX+"_                    "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(Fore.LIGHTGREEN_EX+" \\"+Fore.LIGHTMAGENTA_EX+"____________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"________")
    print(Fore.LIGHTGREEN_EX+"}"+Fore.LIGHTMAGENTA_EX+"<_____________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+"_________>")
    print(Fore.LIGHTGREEN_EX+"_/                     "+Fore.LIGHTCYAN_EX+"\          /")
    print(Fore.LIGHTGREEN_EX+"                        "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print(Fore.LIGHTGREEN_EX+"@_                   "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(Fore.LIGHTGREEN_EX+") \\"+Fore.LIGHTMAGENTA_EX+"___________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"_________")
    print(Fore.LIGHTGREEN_EX+"{}"+Fore.LIGHTMAGENTA_EX+"<____________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+"__________>")
    print(Fore.LIGHTGREEN_EX+")_/                    "+Fore.LIGHTCYAN_EX+"\          /")
    print(Fore.LIGHTGREEN_EX+"@                       "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print(Fore.LIGHTGREEN_EX+"(@_                  "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(Fore.LIGHTGREEN_EX+" ) \\"+Fore.LIGHTMAGENTA_EX+"__________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"__________")
    print(Fore.LIGHTGREEN_EX+"8{}"+Fore.LIGHTMAGENTA_EX+"<___________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+"___________>")
    print(Fore.LIGHTGREEN_EX+" )_/                   "+Fore.LIGHTCYAN_EX+"\          /")
    print(Fore.LIGHTGREEN_EX+"(@                      "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print(Fore.LIGHTGREEN_EX+" (@_                 "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(Fore.LIGHTGREEN_EX+"  ) \\"+Fore.LIGHTMAGENTA_EX+"_________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"_________")
    print(Fore.LIGHTGREEN_EX+"@8{}"+Fore.LIGHTMAGENTA_EX+"<__________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+"__________>")
    print(Fore.LIGHTGREEN_EX+"  )_/                  "+Fore.LIGHTCYAN_EX+"\          /")
    print(Fore.LIGHTGREEN_EX+" (@                     "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print(Fore.LIGHTGREEN_EX+"  (@_                "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(Fore.LIGHTGREEN_EX+"   ) \\"+Fore.LIGHTMAGENTA_EX+"________________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"__________")
    print(Fore.LIGHTGREEN_EX+"8@8{}"+Fore.LIGHTMAGENTA_EX+"<_________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+"___________>")
    print(Fore.LIGHTGREEN_EX+"   )_/                 "+Fore.LIGHTCYAN_EX+"\          /")
    print(Fore.LIGHTGREEN_EX+"  (@                    "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print(Fore.LIGHTGREEN_EX+"   (@_               "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(Fore.LIGHTGREEN_EX+"    ) \\"+Fore.LIGHTMAGENTA_EX+"_______________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"____________")
    print(Fore.LIGHTGREEN_EX+"@8@8{}"+Fore.LIGHTMAGENTA_EX+"<________________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+"_____________>")
    print(Fore.LIGHTGREEN_EX+"    )_/                "+Fore.LIGHTCYAN_EX+"\          /")
    print(Fore.LIGHTGREEN_EX+"   (@                   "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print(Fore.LIGHTGREEN_EX+"    (@_              "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(Fore.LIGHTGREEN_EX+"     ) \\"+Fore.LIGHTMAGENTA_EX+"______________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"_____________")
    print(Fore.LIGHTGREEN_EX+")@8@8{}"+Fore.LIGHTMAGENTA_EX+"<_______________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+"______________>")
    print(Fore.LIGHTGREEN_EX+"     )_/               "+Fore.LIGHTCYAN_EX+"\          /")
    print(Fore.LIGHTGREEN_EX+"    (@                  "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print(Fore.LIGHTGREEN_EX+"     (@_             "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(Fore.LIGHTGREEN_EX+"_     ) \\"+Fore.LIGHTMAGENTA_EX+"_____________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"______________")
    print(Fore.LIGHTGREEN_EX+"_)@8@8{}"+Fore.LIGHTMAGENTA_EX+"<______________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+"_______________>")
    print(Fore.LIGHTGREEN_EX+"      )_/              "+Fore.LIGHTCYAN_EX+"\          /")
    print(Fore.LIGHTGREEN_EX+"     (@                 "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("                      "+Fore.LIGHTCYAN_EX+"/            \\")
    print("                     "+Fore.LIGHTCYAN_EX+"|              |")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print(Fore.LIGHTGREEN_EX+"      (@_            "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(Fore.LIGHTGREEN_EX+" _     ) \\"+Fore.LIGHTMAGENTA_EX+"____________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"_______________")
    print(Fore.LIGHTGREEN_EX+"(_)@8@8{}"+Fore.LIGHTMAGENTA_EX+"<_____________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+"________________>")
    print(Fore.LIGHTGREEN_EX+"       )_/             "+Fore.LIGHTCYAN_EX+"\          /")
    print(Fore.LIGHTGREEN_EX+"      (@                "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
    os.system('clear')
    print(Fore.RESET)
    print("                          "+Fore.LIGHTCYAN_EX+"______")
    print("                       "+Fore.LIGHTCYAN_EX+".-\"      \"-.")
    print("     "+Fore.LIGHTYELLOW_EX+"Excalibur        "+Fore.LIGHTCYAN_EX+"/            \        "+Fore.LIGHTYELLOW_EX+"Made By")
    print("      "+Fore.LIGHTYELLOW_EX+"V 1.0.0        "+Fore.LIGHTCYAN_EX+"|              |     "+Fore.LIGHTYELLOW_EX+"FireKing255")
    print("                     "+Fore.LIGHTCYAN_EX+"|,  "+Fore.LIGHTYELLOW_EX+".-.  .-. "+Fore.LIGHTCYAN_EX+" ,|")
    print("                     "+Fore.LIGHTCYAN_EX+"| )"+Fore.LIGHTYELLOW_EX+"(__/  \__)"+Fore.LIGHTCYAN_EX+"( |")
    print("                     "+Fore.LIGHTCYAN_EX+"|/     /\     \|")
    print(Fore.LIGHTGREEN_EX+"      (@_            "+Fore.LIGHTCYAN_EX+"(_     ^^     _)")
    print(Fore.LIGHTGREEN_EX+" _     ) \\"+Fore.LIGHTMAGENTA_EX+"____________"+Fore.LIGHTCYAN_EX+"\__|"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"|__/"+Fore.LIGHTMAGENTA_EX+"_______________")
    print(Fore.LIGHTGREEN_EX+"(_)@8@8{}"+Fore.LIGHTMAGENTA_EX+"<_____________"+Fore.LIGHTCYAN_EX+"|-\\"+Fore.LIGHTYELLOW_EX+"IIIIII"+Fore.LIGHTCYAN_EX+"/-|"+Fore.LIGHTMAGENTA_EX+"________________>")
    print(Fore.LIGHTGREEN_EX+"       )_/             "+Fore.LIGHTCYAN_EX+"\          /")
    print(Fore.LIGHTGREEN_EX+"      (@                "+Fore.LIGHTCYAN_EX+"`--------` ")
    print("")
    time.sleep(0.02)
